services:
  tux:
    build:
      context: .
      target: dev
    image: ghcr.io/allthingslinux/tux:latest
    container_name: tux
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
          ignore:
            - .venv/
    env_file:
      - .env
    volumes:
      - ./config/:/app/config
      - ./tux/:/app/tux