---

# NOTE: This file is used for production deployment.

services:
  tux:
    container_name: tux
    image: ghcr.io/allthingslinux/tux:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./config:/app/config:ro
      - ./tux:/app/tux
      - ./assets:/app/assets
    env_file:
      - .env
    restart: unless-stopped
