name: "CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  # Python linting (runs only if Python files changed)
  python:
    name: "Python"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for Python changes
        uses: tj-actions/changed-files@v45.0.8
        id: python_changes
        with:
          files: |
            **/*.py
            pyproject.toml
            poetry.lock

      - name: Skip if no Python changes
        if: steps.python_changes.outputs.any_changed != 'true'
        run: |
          echo "No Python files changed, skipping Python quality checks"
          exit 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with=dev,types --no-interaction --no-ansi

      - name: Generate Prisma client
        run: poetry run prisma generate

      - name: Run Ruff formatter check
        run: poetry run ruff format --check

      - name: Run Ruff linter
        run: poetry run ruff check

      - name: Run Pyright type checker
        uses: jakebailey/pyright-action@v2
        with:
          annotate: "errors"

  # Test suite
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for Python changes
        uses: tj-actions/changed-files@v45.0.8
        id: python_changes
        with:
          files: |
            **/*.py
            pyproject.toml
            poetry.lock
            tests/**
            conftest.py

      - name: Skip if no Python/test changes
        if: steps.python_changes.outputs.any_changed != 'true'
        run: |
          echo "No Python or test files changed, skipping tests"
          exit 0

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --with=dev,test,types --no-interaction --no-ansi

      - name: Generate Prisma client
        run: poetry run prisma generate

      - name: Create test environment file
        run: |
          cat > .env << EOF
          DEV_DATABASE_URL=sqlite:///tmp/test.db
          PROD_DATABASE_URL=sqlite:///tmp/test.db
          DEV_BOT_TOKEN=test_token_for_ci
          PROD_BOT_TOKEN=test_token_for_ci
          EOF

      - name: Run unit tests with coverage
        run: poetry run pytest tests/ -v --cov=tux --cov-branch --cov-report=xml:coverage-unit.xml --cov-report=term-missing -m "not slow and not docker" --junitxml=junit-unit.xml -o junit_family=legacy --cov-fail-under=0

      - name: Debug coverage file before upload
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)
        run: |
          echo "Checking coverage files..."
          ls -la coverage-*.xml || echo "No coverage files found"
          if [ -f ./coverage-unit.xml ]; then
            echo "Unit coverage file size: $(stat -c%s ./coverage-unit.xml) bytes"
            echo "Unit coverage file first few lines:"
            head -n 5 ./coverage-unit.xml || echo "Could not read coverage file"
          else
            echo "Unit coverage file not found"
          fi

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@v5
        if: (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && hashFiles('./coverage-unit.xml') != ''
        with:
          files: ./coverage-unit.xml
          flags: unit
          name: unit-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: allthingslinux/tux
          fail_ci_if_error: false
          verbose: true
          disable_search: true

      - name: Upload unit test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          file: ./junit-unit.xml
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}

      # Check if database tests exist before running them
      - name: Check for database tests
        id: check_db_tests
        run: |
          if find tests/tux/database/ -name "test_*.py" -type f | grep -q .; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
            echo "Database tests found"
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
            echo "No database tests found, skipping database test suite"
          fi

      # Run database-specific tests with dedicated flag (only if tests exist)
      - name: Run database tests with coverage
        if: steps.check_db_tests.outputs.has_tests == 'true'
        run: poetry run pytest tests/tux/database/ -v --cov=tux/database --cov-branch --cov-report=xml:coverage-database.xml --junitxml=junit-database.xml -o junit_family=legacy --cov-fail-under=0

      - name: Upload database test coverage to Codecov
        if: steps.check_db_tests.outputs.has_tests == 'true' && (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository)) && hashFiles('./coverage-database.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage-database.xml
          flags: database
          name: database-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: allthingslinux/tux
          fail_ci_if_error: false
          verbose: true
          disable_search: true

      - name: Upload database test results to Codecov
        if: steps.check_db_tests.outputs.has_tests == 'true' && !cancelled()
        uses: codecov/test-results-action@v1
        with:
          file: ./junit-database.xml
          flags: database
          token: ${{ secrets.CODECOV_TOKEN }}

      # Check if integration tests (slow tests) exist before running them
      - name: Check for integration tests
        if: github.event_name == 'push' # Only on main branch pushes to save CI time
        id: check_integration_tests
        run: |
          if poetry run pytest --collect-only -m "slow" -q tests/ | grep -q "test session starts"; then
            echo "has_tests=true" >> $GITHUB_OUTPUT
            echo "Integration tests found"
          else
            echo "has_tests=false" >> $GITHUB_OUTPUT
            echo "No integration tests found, skipping integration test suite"
          fi

      # Optional: Run integration tests separately (if you have them)
      - name: Clean up previous coverage files before integration tests
        if: github.event_name == 'push' && steps.check_integration_tests.outputs.has_tests == 'true'
        run: |
          echo "Cleaning up previous coverage files to avoid conflicts..."
          rm -f coverage-unit.xml coverage-database.xml || true
          echo "Current coverage files:"
          ls -la coverage-*.xml 2>/dev/null || echo "No coverage files found"

      - name: Run integration tests with coverage
        if: github.event_name == 'push' && steps.check_integration_tests.outputs.has_tests == 'true'
        run: poetry run pytest tests/ -v --cov=tux --cov-branch --cov-report=xml:coverage-integration.xml -m "slow" --junitxml=junit-integration.xml -o junit_family=legacy --cov-fail-under=0
        continue-on-error: true # Don't fail CI if integration tests fail

      - name: Upload integration test coverage to Codecov
        if: github.event_name == 'push' && steps.check_integration_tests.outputs.has_tests == 'true' && hashFiles('./coverage-integration.xml') != ''
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage-integration.xml
          flags: integration
          name: integration-tests
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: allthingslinux/tux
          fail_ci_if_error: false
          verbose: true
          disable_search: true

      - name: Upload integration test results to Codecov
        if: github.event_name == 'push' && steps.check_integration_tests.outputs.has_tests == 'true' && !cancelled()
        uses: codecov/test-results-action@v1
        with:
          file: ./junit-integration.xml
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}

  # Matrix strategy for file linting with inline configs
  lint:
    name: "Lint (${{ matrix.type }})"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: "YAML"
            files: "**/*.yml,**/*.yaml"
          - type: "JSON"
            files: "**/*.json"
          - type: "Markdown"
            files: "**/*.md"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for ${{ matrix.type }} changes
        uses: tj-actions/changed-files@v45.0.8
        id: file_changes
        with:
          files: ${{ matrix.files }}

      - name: Skip if no ${{ matrix.type }} changes
        if: steps.file_changes.outputs.any_changed != 'true'
        run: |
          echo "No ${{ matrix.type }} files changed, skipping ${{ matrix.type }} linting"
          exit 0

      - name: Skip formatting checks for pushes to main (protected branch)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "ℹ️ Skipping ${{ matrix.type }} formatting checks for push to protected main branch"
          echo "Formatting should have been handled in the PR before merge"
          exit 0

      - name: Setup Node.js
        if: matrix.type != 'YAML'
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Python (with cache)
        if: matrix.type == 'YAML'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install linting tools
        run: |
          if [ "${{ matrix.type }}" = "YAML" ]; then
            pip install yamllint
            npm install -g prettier
          elif [ "${{ matrix.type }}" = "JSON" ]; then
            npm install -g prettier
          elif [ "${{ matrix.type }}" = "Markdown" ]; then
            npm install -g markdownlint-cli
          fi

      - name: Run YAML linting with inline config
        if: matrix.type == 'YAML'
        run: |
          # Create inline yamllint config
          cat > /tmp/yamllint.yml << 'EOF'
          extends: default
          rules:
            line-length:
              max: 120
              level: warning
            document-start: disable
            truthy:
              allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
          ignore: |
            .venv/
            .archive/
            node_modules/
            typings/
          EOF

          # Run yamllint with inline config
          yamllint --config-file /tmp/yamllint.yml .

          # Run prettier with inline config
          # Only auto-fix on PRs from same repo (not forks or protected main branch)
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            echo "🔧 Auto-fixing YAML formatting issues..."
            npx prettier --write \
              --tab-width 2 \
              --print-width 120 \
              --end-of-line lf \
              "**/*.{yml,yaml}" \
              --ignore-path <(echo -e ".venv/\n.archive/\nnode_modules/\ntypings/\npoetry.lock\nflake.lock")
          else
            echo "⚠️ Fork detected - checking only (no auto-fix)"
            npx prettier --check \
              --tab-width 2 \
              --print-width 120 \
              --end-of-line lf \
              "**/*.{yml,yaml}" \
              --ignore-path <(echo -e ".venv/\n.archive/\nnode_modules/\ntypings/\npoetry.lock\nflake.lock")
          fi

      - name: Run JSON linting with inline config
        if: matrix.type == 'JSON'
        run: |
          # Only auto-fix on PRs from same repo (not forks or protected main branch)
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.pull_request.head.repo.full_name }}" == "${{ github.repository }}" ]]; then
            echo "🔧 Auto-fixing JSON formatting issues..."
            npx prettier --write \
              --tab-width 2 \
              --print-width 80 \
              --end-of-line lf \
              "**/*.json" \
              --ignore-path <(echo -e ".venv/\n.archive/\nnode_modules/\ntypings/\npoetry.lock")
          else
            echo "⚠️ Fork detected - checking only (no auto-fix)"
            npx prettier --check \
              --tab-width 2 \
              --print-width 80 \
              --end-of-line lf \
              "**/*.json" \
              --ignore-path <(echo -e ".venv/\n.archive/\nnode_modules/\ntypings/\npoetry.lock")
          fi

      - name: Run Markdown linting with inline config
        if: matrix.type == 'Markdown'
        run: |
          # Run markdownlint with inline rules
          npx markdownlint \
            --disable MD013 MD033 MD041 \
            --ignore node_modules \
            --ignore .venv \
            --ignore .archive \
            "**/*.md"

      - name: Commit formatting fixes
        if: steps.file_changes.outputs.any_changed == 'true' && (matrix.type == 'JSON' || matrix.type == 'YAML') && github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
        run: |
          # Configure Git
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Check if there are changes to commit
          if ! git diff --quiet; then
            git add .
            git commit -m "style: auto-fix ${{ matrix.type }} formatting issues [skip ci]"
            git push
            echo "✅ Committed ${{ matrix.type }} formatting fixes"
          else
            echo "ℹ️ No ${{ matrix.type }} formatting changes needed"
          fi

  # Infrastructure linting
  infrastructure:
    name: "Infrastructure (${{ matrix.type }})"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - type: "Docker"
            files: "Dockerfile*,docker-compose*.yml"
          - type: "GitHub Actions"
            files: ".github/workflows/**"
          - type: "Shell Scripts"
            files: "**/*.sh,**/*.bash,scripts/**"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for ${{ matrix.type }} changes
        uses: tj-actions/changed-files@v45.0.8
        id: infra_changes
        with:
          files: ${{ matrix.files }}

      - name: Skip if no ${{ matrix.type }} changes
        if: steps.infra_changes.outputs.any_changed != 'true'
        run: |
          echo "No ${{ matrix.type }} files changed, skipping ${{ matrix.type }} linting"
          exit 0

      - name: Set up Docker Compose v2
        if: matrix.type == 'Docker'
        run: |
          # Docker Compose v2 is pre-installed on GitHub runners
          # Just verify it's available and supports the develop configuration
          docker compose version
          echo "✅ Docker Compose v2 is available"

      - name: Create .env file for Docker Compose validation
        if: matrix.type == 'Docker'
        run: |
          # Create .env file for CI validation with minimal required values
          cat > .env << EOF
          DEV_DATABASE_URL=sqlite:///tmp/test.db
          PROD_DATABASE_URL=sqlite:///tmp/test.db
          DEV_BOT_TOKEN=test_token_for_ci_validation
          PROD_BOT_TOKEN=test_token_for_ci_validation
          EOF

      - name: Run Docker linting
        if: matrix.type == 'Docker'
        run: |
          # Hadolint with inline config
          docker run --rm -i hadolint/hadolint hadolint \
            --ignore DL3008 \
            --ignore DL3009 \
            - < Dockerfile

          # Docker Compose validation (compatible with older versions)
          # Check if docker compose (v2) is available, fallback to docker-compose (v1)
          if command -v docker compose >/dev/null 2>&1; then
            echo "Using Docker Compose v2"
            docker compose -f docker-compose.yml config --quiet
            docker compose -f docker-compose.dev.yml config --quiet
          elif command -v docker-compose >/dev/null 2>&1; then
            echo "Using Docker Compose v1"
            docker-compose -f docker-compose.yml config --quiet
            docker-compose -f docker-compose.dev.yml config --quiet
          else
            echo "Neither docker compose nor docker-compose found"
            exit 1
          fi

      - name: Run GitHub Actions linting
        if: matrix.type == 'GitHub Actions'
        uses: raven-actions/actionlint@v1
        with:
          files: ".github/workflows/*.yml"

      - name: Run Shell linting
        if: matrix.type == 'Shell Scripts'
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "./scripts"
