name: "Ruff - Linting and Formatting"

on: [push, pull_request]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  Ruff:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}

      # Install Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      # Install Ruff
      - name: Install Ruff
        run: sudo snap install ruff

      # Run Ruff linter
      - name: Run Ruff format
        run: ruff format && ruff check . --fix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Linting and formatting via Ruff"
