on:
  workflow_dispatch:
    inputs:
        KEEP_AMOUNT:
            description: "Number of images to keep"
            required: true
            default: "10"

jobs:
  remove-old-images:
    runs-on: ubuntu-latest

    steps:
      - name: Remove old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'tux'
          package-type: 'container'
          min-versions-to-keep: 10
