name: "TODO to Issue"

on:
  push:
  workflow_dispatch:
    inputs:
      MANUAL_COMMIT_REF:
        description: "SHA to compare"
        required: true
      MANUAL_BASE_REF:
        description: "Optional earlier SHA"
        required: false

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@master"
        env:
          MANUAL_COMMIT_REF: ${{ inputs.MANUAL_COMMIT_REF }}
          MANUAL_BASE_REF: ${{ inputs.MANUAL_BASE_REF }}
        with:
          PROJECTS_SECRET: ${{ secrets.ADMIN_PAT }}
          AUTO_CLOSE: true  # recommended
          IGNORE_COMMENTS: false
          LABEL: "auto-todos"
